export const defaultDrivers = [
  "Khang",
  "Nghị",
  "Vinh",
  "Thành",
  "Tuấn",
  "Nhựt",
  "Vương",
  "Phát",
  "Khải",
  "Phương"
];

export const defaultVehicles = ["DOTHANH", "SU LỚN", "SU NHỎ", "KIA", "HINO"];

export const defaultBranches = [
  "Thanh Bình",
  "Thạnh Phú",
  "Long Xuyên",
  "Thốt Nốt",
  "Cà Mau",
  "Kho BD (Hàng Đông)",
  "Kho BD (Súp)",
  "Cái Tàu",
  "An Long",
  "Ba Tri",
  "Rạch Giá",
  "Lấp Vò",
  "Phước Long",
  "Kiến Tường",
  "Hòa Phú",
  "Hồng Ngự",
  "Bình Đại",
  "Kiên Lương",
  "Cờ Đỏ",
  "Năm Căn",
  "Thạnh Hoá",
  "Lai Vung",
  "Tân Hồng",
  "Mỏ Cày",
  "Tri Tôn",
  "Vị Thanh",
  "Giá Rai",
  "Đức Huệ",
  "Đại Học",
  "Tam Nông",
  "Cái Bè",
  "Thoại Sơn",
  "Thới Lai",
  "Sông Đốc",
  "Tân Thạnh",
  "Tân Hưng",
  "Cai Lậy",
  "Nhà Bàng",
  "Một Ngàn",
  "Đầm Dơi",
  "Tháp Mười",
  "Vĩnh Hưng",
  "Mỹ Tho",
  "Hòn Đất",
  "Trung An",
  "Thới Bình",
  "Trường Xuân",
  "An Phong",
  "Chợ Gạo",
  "An Châu",
  "Ô Môn",
  "Ngan Dừa",
  "Phú Tân",
  "Tân Bình",
  "Bình Minh",
  "Vĩnh Bình",
  "Tân Hiệp",
  "Nàng Mau",
  "Cái Nước",
  "Chợ Mới",
  "Tân Thành",
  "Bình Tân",
  "Gò Công",
  "Phú Hòa",
  "Phong Điền",
  "An Biên",
  "Mỹ Luông",
  "Phú Quốc",
  "Tam Bình",
  "Gò Đen",
  "An Phú",
  "Tiểu Cần",
  "Vĩnh Thuận",
  "Long Mỹ",
  "Cao Lãnh",
  "Vĩnh Long",
  "Cần Đước",
  "Châu Phú",
  "Trà Ôn",
  "Ngã 7",
  "Ngã 5 Sóc Trăng",
  "Chiba Cao Lãnh",
  "Kế Sách",
  "Tân An",
  "Quốc Thái",
  "Kho Trà Vinh",
  "Cái Tắc",
  "Phú Lộc",
  "Mái Dầm",
  "Tân Hương",
  "Gò Quao",
  "TP Cần Thơ",
  "Châu Thành - Sóc Trăng",
  "Hòa Bình",
  "Ngã 6",
  "Chợ Lách",
  "Giồng Riềng",
  "Trần Văn Thời",
  "Bạc Liêu",
  "Long Phú",
  "Giồng Trôm",
  "Rạch Sỏi",
  "T.T Thứ 11",
  "Chợ Vàm",
  "Vĩnh Châu",
  "Châu Đốc",
  "Hà Tiên",
  "Tắc Vân",
  "Cần Thơ",
  "Trà Vinh",
  "Ba Chúc",
  "Trần Đề"
];
